#!/bin/sh
#
# A git hook to make sure user.email exists before committing

EMAIL=$(git config user.email)
NAME=$(git config user.name)
if [ -z "$EMAIL" ] || [ -z "$NAME" ]; then  
    # user.email is empty
    echo "ERROR: [pre-commit hook] Aborting commit because user.email or user.name is missing. Configure them for this repository. Make sure not to configure globally."
    exit 1
else  
    # user.email is not empty
    exit 0
fi 
